apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
  labels:
    app: expense-tracker
type: Opaque
data:
  # Base64-encoded MongoDB connection string
  # Replace with your own: echo -n "your-mongo-uri" | base64
  mongo-uri: bW9uZ29kYitzcnY6Ly91c2VyOnBhc3NAY2x1c3Rlci5leGFtcGxlLm1vbmdvZGIubmV0L2V4cGVuc2VfdHJhY2tlcg==
